### PR TITLE
Front End pseudocontent

### PR DESCRIPTION
**Pull request by kvangreen**
Added pseudocontent for FAQ and About. Created Account page and updated controller/route accordingly. Added navbar to application layout. Could not test due to rackup errors.

### CODE REVIEW

**Review by sunniraleigh — APPROVED** [review]
looks good

**Review by luciebrock — COMMENTED** [review]
nice!

**Review by luciebrock — APPROVED** [review]
I think this is good

**Review by amarrap — APPROVED** [review]
gorgeous gorgeous navbar <3

**Review by epartakki — APPROVED** [review]
we just need to solve the conflict with routes

**Pull request merged**
